name: Deploy to Pantheon after building assets

on:
  push:

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy with built assets to Pantheon
    steps:
      - name: Checkout this branch
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Install PHP dependencies
        uses: php-actions/composer@v6

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install npm dependencies
        run: |
          npm ci --legacy-peer-deps

      - name: Build assets
        run: |
          npm run build

      - name: Authenticate with Pantheon codeserver repo
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PANTHEON_PRIVATE_KEY }}

      - name: Deploy built files
        run: |
          bash .github/workflows/update-built-branch.sh
        env:
          PANTHEON_PROJECT_ID: 65401411-429a-476e-8dc8-4bd98e5d9164
          PANTHEON_MACHINE_KEY: ${{ secrets.PANTHEON_MACHINE_KEY }}
